### ISSUE TITLE
Deckstat: Format for collection and decks are different

### ISSUE THREAD

**Issue by Frexxxy** [raeffs/deck-bridge#3]
The current format from the export is optimized for the collection (version, language, etc).

![image](https://user-images.githubusercontent.com/47367478/218246186-2eeb10a1-48a9-48ef-9147-0e058568dd62.png)

For the decks only the number and the card name is relevant in the export:
https://deckstats.net/forum/index.php/topic,54267.0.html
![image](https://user-images.githubusercontent.com/47367478/218246244-12dc4dfa-cde9-40b3-b49f-ffa84fbfedd3.png)

**Comment by raeffs** [comment]
should work with `--to DeckstatsDeck` now
